-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Create the Table
create table public.trucks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  plat text not null,
  status text default 'WAITING',
  remarks text,

  -- Timestamps
  tgl_berangkat date,
  jam_berangkat text, -- Storing time as text (HH:mm) is easier for HTML inputs
  tgl_tiba date,
  jam_tiba text,
  jam_bongkar text,
  jam_selesai text,
  is_archived boolean default false -- New column for History feature
);

-- 2. Enable Realtime (So updates show instantly)
alter publication supabase_realtime add table public.trucks;

-- 3. Policy (Allow anyone with the Key to Read/Write - Public Board)
alter table public.trucks enable row level security;

create policy "Enable access for all users"
on public.trucks
for all
using (true)
with check (true);

-- 4. Create Archive Index (Optional but good for performance)
create index idx_trucks_archived on public.trucks(is_archived);
